/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "test_kv_db.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SimplePODData, SimplePODData, AUTO)


PB_BIND(KindaComplexPODData, KindaComplexPODData, AUTO)


PB_BIND(StringData, StringData, AUTO)


PB_BIND(GyroSensorData, GyroSensorData, AUTO)



