/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -s c++20
 */

#include "time_intf_expect.hpp"

namespace expect { namespace mb$ { namespace time$ {
MockExpectedCall& millis(size_t __return__)
{
    return millis(1, __return__);
}
MockExpectedCall& millis(unsigned int __numCalls__, size_t __return__)
{
    MockExpectedCall& __expectedCall__ = mock().expectNCalls(__numCalls__, "mb::time::millis");
    __expectedCall__.andReturnValue(static_cast<unsigned long>(__return__));
    return __expectedCall__;
}
} } }

namespace expect { namespace mb$ { namespace time$ {
MockExpectedCall& micros(size_t __return__)
{
    return micros(1, __return__);
}
MockExpectedCall& micros(unsigned int __numCalls__, size_t __return__)
{
    MockExpectedCall& __expectedCall__ = mock().expectNCalls(__numCalls__, "mb::time::micros");
    __expectedCall__.andReturnValue(static_cast<unsigned long>(__return__));
    return __expectedCall__;
}
} } }

